# Generated by Django 5.1.7 on 2025-04-04 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_user_phone_number_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
