# Generated by Django 5.1.7 on 2025-04-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignmentorder_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentorder',
            name='drop_location',
        ),
        migrations.RemoveField(
            model_name='assignmentorder',
            name='extra_charge',
        ),
        migrations.RemoveField(
            model_name='assignmentorder',
            name='pickup_distance_km',
        ),
        migrations.RemoveField(
            model_name='assignmentorder',
            name='pickup_location',
        ),
    ]
